openapi: 3.0.0
info:
  title: Translator service between a srb2kart server and json
  version: 0.0.1
servers:
- url: http://translator:5092
paths:
  /playerinfo:
    get:
      description: Returns the PT_PLAYERINFO data from the server containing information
        about the current players
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerInfo'
          description: success
      summary: get the player infomation
  /serverinfo:
    get:
      description: Returns the PT_SERVERINFO data from the server containing information
        about the state of the server
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerInfo'
          description: success
      summary: get the server information
  /files:
    get:
      description: Returns the PT_TELLFILESNEEDED data from the server containing
        information about the installed mods
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllFilesNeeded'
          description: success
      summary: get the installed files
components:
  schemas:
    CheckSum:
      items:
        type: number
      type: array
    AllFilesNeeded:
      items:
        type: string
      type: array
    FileNeeded:
      items:
        $ref: '#/components/schemas/FileNeeded_inner'
      type: array
    PlayerInfoEntry:
      example:
        Score: 5.637376656633329
        TimeInServer: 2.3021358869347655
        Address: Address
        Node: 0.8008281904610115
        Team: 6.027456183070403
        Skin: 1.4658129805029452
        Data: 5.962133916683182
        Name: Name
      properties:
        Node:
          type: number
        Name:
          type: string
        Address:
          type: string
        Team:
          type: number
        Skin:
          type: number
        Data:
          type: number
        Score:
          type: number
        TimeInServer:
          type: number
      type: object
    PlayerInfo:
      items:
        $ref: '#/components/schemas/PlayerInfoEntry'
      type: array
    ServerInfo:
      example:
        ActNum: 7.386281948385884
        HttpSource: HttpSource
        FileNeeded:
        - WillSend: true
          FileName: FileName
          TotalSize: 1.2315135367772556
          MD5:
          - 1.0246457001441578
          - 1.0246457001441578
        - WillSend: true
          FileName: FileName
          TotalSize: 1.2315135367772556
          MD5:
          - 1.0246457001441578
          - 1.0246457001441578
        IsZone: true
        ModifiedGame: true
        PacketVersion: 0.8008281904610115
        Time: 3.616076749251911
        GameType: 2.3021358869347655
        LevelTime: 2.027123023002322
        KartVars: 7.061401241503109
        SubVersion: 1.4658129805029452
        MaxPlayers: 5.637376656633329
        MapName: MapName
        MapMD5:
        - 4.145608029883936
        - 4.145608029883936
        CheatsEnabled: true
        Version: 6.027456183070403
        NumberOfPlayer: 5.962133916683182
        ServerName: ServerName
        MapTitle: MapTitle
        FileNeededNum: 9.301444243932576
        Application: Application
        ServerNameRaw: ServerNameRaw
      properties:
        PacketVersion:
          type: number
        Application:
          type: string
        Version:
          type: number
        SubVersion:
          type: number
        NumberOfPlayer:
          type: number
        MaxPlayers:
          type: number
        GameType:
          type: number
        ModifiedGame:
          type: boolean
        CheatsEnabled:
          type: boolean
        KartVars:
          type: number
        FileNeededNum:
          type: number
        Time:
          type: number
        LevelTime:
          type: number
        ServerNameRaw:
          type: string
        ServerName:
          type: string
        MapName:
          type: string
        MapTitle:
          type: string
        MapMD5:
          items:
            type: number
          type: array
        ActNum:
          type: number
        IsZone:
          type: boolean
        HttpSource:
          type: string
        FileNeeded:
          items:
            $ref: '#/components/schemas/FileNeeded_inner'
          type: array
      type: object
    FileNeeded_inner:
      example:
        WillSend: true
        FileName: FileName
        TotalSize: 1.2315135367772556
        MD5:
        - 1.0246457001441578
        - 1.0246457001441578
      properties:
        WillSend:
          type: boolean
        TotalSize:
          type: number
        FileName:
          type: string
        MD5:
          items:
            type: number
          type: array
      type: object
